"""Add validation tasks, runs and logs.

Introduces ``validation_runs`` (versioned validation passes over an
application), ``validation_tasks`` (the queueable unit of work driving a run
through PENDING / IN_REVIEW / NEEDS_CORRECTION / VALIDATED / REJECTED) and
``validation_logs`` (the immutable, append-only audit trail of every validation
event). The new enums mirror the ``app.database.models.enums`` definitions; no
user/operator columns are added -- those arrive with the separate User/Operator
module.

Revision ID: a3f9b7c1d4e2
Revises: 1b81ff3e40cd
Create Date: 2026-08-13 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f9b7c1d4e2'
down_revision: Union[str, Sequence[str], None] = '1b81ff3e40cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    validationtaskstatus = sa.Enum(
        'PENDING', 'IN_REVIEW', 'NEEDS_CORRECTION', 'VALIDATED', 'REJECTED',
        name='validationtaskstatus',
    )
    validationtaskpriority = sa.Enum(
        'LOW', 'NORMAL', 'HIGH', 'URGENT',
        name='validationtaskpriority',
    )
    validationlogaction = sa.Enum(
        'TASK_CREATED', 'TASK_STARTED', 'FIELD_VERIFIED', 'FIELD_CORRECTED',
        'BUSINESS_RULE_REVIEWED', 'SIGNATURE_REVIEWED', 'STAMP_REVIEWED',
        'ORIGINALITY_REVIEWED', 'DOCUMENT_REVIEWED', 'CORRECTION_REQUESTED',
        'VALIDATION_COMPLETED', 'VALIDATION_REJECTED', 'REVALIDATION_STARTED',
        name='validationlogaction',
    )
    validationlogchecktype = sa.Enum(
        'ACCOUNT_NUMBER', 'NTN', 'BANK_NAME', 'ACCOUNT_TITLE', 'SIGNATURE',
        'STAMP', 'BUSINESS_RULE', 'BANK_MAINTENANCE_ORIGINALITY',
        'DOCUMENT_REVIEW', 'GENERAL',
        name='validationlogchecktype',
    )
    validationlogresult = sa.Enum(
        'PASS', 'FAIL', 'CONFIRMED', 'CORRECTED', 'REQUIRES_REVIEW', 'REJECTED',
        'REVIEWED', 'INFO',
        name='validationlogresult',
    )

    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_validation_runs_applications_application_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_runs')),
    sa.UniqueConstraint('application_id', 'run_number', name=op.f('uq_validation_runs_application_id_run_number'))
    )
    op.create_index('ix_validation_runs_application_id', 'validation_runs', ['application_id'], unique=False)

    op.create_table('validation_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', validationtaskstatus, server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('priority', validationtaskpriority, server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_validation_tasks_applications_application_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_validation_tasks_validation_runs_validation_run_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_tasks'))
    )
    op.create_index('ix_validation_tasks_application_id', 'validation_tasks', ['application_id'], unique=False)
    op.create_index('ix_validation_tasks_created_at', 'validation_tasks', ['created_at'], unique=False)
    op.create_index('ix_validation_tasks_priority', 'validation_tasks', ['priority'], unique=False)
    op.create_index('ix_validation_tasks_queue', 'validation_tasks', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('ix_validation_tasks_status', 'validation_tasks', ['status'], unique=False)

    op.create_table('validation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('validation_task_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=True),
    sa.Column('action', validationlogaction, nullable=False),
    sa.Column('check_type', validationlogchecktype, nullable=True),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('result', validationlogresult, nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_validation_logs_applications_application_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_validation_logs_validation_runs_validation_run_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_task_id'], ['validation_tasks.id'], name=op.f('fk_validation_logs_validation_tasks_validation_task_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_logs'))
    )
    op.create_index('ix_validation_logs_action', 'validation_logs', ['action'], unique=False)
    op.create_index('ix_validation_logs_application_id', 'validation_logs', ['application_id'], unique=False)
    op.create_index('ix_validation_logs_check_type', 'validation_logs', ['check_type'], unique=False)
    op.create_index('ix_validation_logs_created_at', 'validation_logs', ['created_at'], unique=False)
    op.create_index('ix_validation_logs_task_created_at', 'validation_logs', ['validation_task_id', 'created_at'], unique=False)
    op.create_index('ix_validation_logs_validation_run_id', 'validation_logs', ['validation_run_id'], unique=False)
    op.create_index('ix_validation_logs_validation_task_id', 'validation_logs', ['validation_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_logs_validation_task_id', table_name='validation_logs')
    op.drop_index('ix_validation_logs_validation_run_id', table_name='validation_logs')
    op.drop_index('ix_validation_logs_task_created_at', table_name='validation_logs')
    op.drop_index('ix_validation_logs_created_at', table_name='validation_logs')
    op.drop_index('ix_validation_logs_check_type', table_name='validation_logs')
    op.drop_index('ix_validation_logs_application_id', table_name='validation_logs')
    op.drop_index('ix_validation_logs_action', table_name='validation_logs')
    op.drop_table('validation_logs')

    op.drop_index('ix_validation_tasks_status', table_name='validation_tasks')
    op.drop_index('ix_validation_tasks_queue', table_name='validation_tasks')
    op.drop_index('ix_validation_tasks_priority', table_name='validation_tasks')
    op.drop_index('ix_validation_tasks_created_at', table_name='validation_tasks')
    op.drop_index('ix_validation_tasks_application_id', table_name='validation_tasks')
    op.drop_table('validation_tasks')

    op.drop_index('ix_validation_runs_application_id', table_name='validation_runs')
    op.drop_table('validation_runs')

    sa.Enum(name='validationlogresult').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='validationlogchecktype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='validationlogaction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='validationtaskpriority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='validationtaskstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
